service:
  name: serverless-http-echo

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
